### ISSUE TITLE
2010年～2014年の90歳以上のデータについて

### ISSUE THREAD

**Issue by nanachan2020** [taisukef/info-highschool#1]
2010年～2014年の90歳以上のデータについては年齢別にデータがとれていないので
グラフにするとおかしいような気がします。
GitHubを使ったことがあまりないので意見・質問がある場合ここですればよいのか
よくわかりませんが・・・・

**Comment by taisukef** [comment]
はい、そう思います
まずはシンプルにCSVオープンデータをグラフにすることができることを体験してもらうのが先と考え、そのままにしています
異常値を見てその原因を推測し、どう修正するか考え、やってみるまでもよい学びになるはずです

**Comment by nanachan2020** [comment]
なるほど。私はすでに高校教員を退職した身分ですが情報を担当していたので
GGながら勉強させていただいております。
この前オンラインでIchigoJamも経験させていただきました。
さしつかえなかったらいろいろと教えてください。
コメントはCloseしておけばよいですね。

**Comment by taisukef** [comment]
本職の方でしたか！
IchigoJamのご利用もありがとうございます
小学生から大人まで、まずはコンピューターのスゴさと限界と可能性を知ってほしいですね
ぜひいろいろな観点でのIssue（課題）お願いします！
